### ISSUE TITLE
IPAddressClaim should have a ready status condition, and should be set false when referenced pool is not found

### ISSUE THREAD

**Issue by tylerschultz** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#111]
In the case that an IPAddressClaim references a InClusterIPPool that does not exist, the claim should be marked 
ready: false, with reason: "Pool not found".

This leaves also the opportunity for other reasons, such as "Pool depleted" and such.

**Comment by tylerschultz** [comment]
We spent some time looking into adding a condition for when a pool is not found, but ran into some problems.

• The IPAddressClaim (which lives in cluster-api) does not conform to the `conditions.Setter` interface, so the conditions helper functions seen throughout cluster-api repos won't work without updating.
• The IPAddressClaimStatus.AddressRef is not optional. This means that it is impossible to set a Status Condition on a claim when there is no associated IPAddress.

These problems make this a larger effort than expected. We think we'll regroup and gather up all of the changes we think should go into cluster-api ipam CRDs and make a PR when we know more. We can revisit this feature then.

**Comment by schrej** [comment]
It does in the latest version: https://github.com/kubernetes-sigs/cluster-api/pull/8374

We also have an issue to standardise this a bit, so it's consistent between providers. Would be great to get some more input there: https://github.com/kubernetes-sigs/cluster-api/issues/8424

**Comment by tylerschultz** [comment]
Ah, my goodness, we'll take a look and try to get up to speed. Thanks.
