### ISSUE TITLE
IPAddressClaim controller should detect cluster paused consistently

### ISSUE THREAD

**Issue by tylerschultz** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#136]
Changes were recently made to the IPAddressClaim controller to prevent reconciliation when the `Cluster` object is paused. The `Cluster` object has a `spec.Paused` property, and can also have a Paused annotation. The code copied from CAPV and placed into the IPAddressClaim controller looks at the `Cluster`'s `spec.Paused` property during updates, and looks at the `Cluster`'s paused annotations during creates. It seems the Update and Create functions should both look at both the annotation and the property.

https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/main/internal/controllers/ipaddressclaim.go#L76-L88

We thought this was odd and @srm09 agreed. We opened this issue on CAPV as a result of our discussion. 

https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/issues/1890

Sagar suggests this paused detection predicate should be a shared library function owned by either CAPV or CAPI, and all controllers should detect paused in the same. This issue is a reminder to update the IPAddressClaim controller when the CAPV issue is resolved.

**Comment by schrej** [comment]
Yes, we should use [`annotations.IsPaused()`](https://pkg.go.dev/sigs.k8s.io/cluster-api/util/annotations#IsPaused) instead of `annotations.HasPaused()`.
