### ISSUE TITLE
Controller shouldn't allocate IP addresses that are "reserved" for the subnet

### ISSUE THREAD

**Issue by christianang** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#165]
# Context

Broken out of the conversation started in https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/pull/123#discussion_r1200845468.

There are ip addresses that shouldn't be given out that are reserved for special cases in the subnet. This is typically the network address, the broadcast address, and the gateway address.

# Proposed Solution

If I defined the following pool:
```
Gateway: 192.168.0.1
Prefix: 16
Addresses:
- 192.168.0.0/16
```

The controller should not allocate: 192.168.0.0 (network address), 192.168.0.1 (gateway address), 192.168.255.255 (broadcast address). It would therefore give out 192.168.0.2-192.168.255.254.

If a user wants to allocate reserved addresses i.e ignore the above functionality except for gateway, a user can set a new flag called `allocatedReservedAddresses`, which would allocate 192.168.0.0-192.168.255.255 (except for 192.168.0.1). If the user doesn't want to reserve the gateway they should not set the gateway.

**Comment by schrej** [comment]
I think we should never allocate the gateway address as it's explicitly specified and I don't think that allocating the gateway address to a random machine is a use case.
The other two reserved addresses are not configured explicitly, and there are use cases where you don't need them to be reserved.

**Comment by christianang** [comment]
Yeah that makes sense. Updated the body of the issue.

**Comment by tylerschultz** [comment]
FYI - we're taking a hack at this issue
