### ISSUE TITLE
Handle reserved Ips withing an IP range

### ISSUE THREAD

**Issue by mcbenjemaa** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#180]
Wen are trying to integrate this provider as part of our infrastructure in Proxmox.

But we couldn't find any way of handling reserved IPs.

As we use this IPAM provider to get ip addresses to set to our machines, but there's no way of setting an already 
existent IP. 
which means, that would end up in a conflicts.

for example we have an IPrange: 10.10.10.1/24 and gateway: 10.10.10.1

In our range, we would have some Machines running , e.g. jumphosts, CI, dhcp server, or VMs used for maintenance.

so, if we have a manual machine provisioned to this network with ip e.g. `10.10.10.3`,

How to tell IPAM provider to no use this IP?

**Comment by schrej** [comment]
Currently this is only possible by explicitly specifying which ranges should be used. In this case by writing
```yaml
addresses:
- 10.10.10.2
- 10.10.10.4-10.10.10.255
```
That's not a great way of course. We can consider adding a `exclude` or `reserved` field to make this easier.

**Comment by lubedacht** [comment]
That would be nice and also increase the readability of the configuration. Also makes things easier, if you for instance rather intend to provide a CIDR block instead of ranges.

**Comment by Sajiyah-Salat** [comment]
Hello @schrej I would like to take this up and want to start my contribution journey. Can you please specify the exact location where the change needed? Also it will be helpful if you give me some working solution adn explain the issue in detail
Thank you!

**Comment by schrej** [comment]
Hey @Sajiyah-Salat, happy to hear that!
First, you'll need to extend the [InClusterIPPoolSpec](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/blob/main/api/v1alpha2/inclusterippool_types.go#L24) with a new string list field to list excluded addresses and ranges. I'd call it `exclude` or something similar.
Then you need to update the [PoolSpecToIPSet](https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/blob/main/internal/poolutil/pool.go#L105) function in the `internal/poolutil` package to remove any addresses or ranges listed in the `excluded` field.
Finally a few tests to verify that the feature works as intended would be great!

I hope that helps you to get started.

**Comment by mcbenjemaa** [comment]
@schrej 

Wouldn't be helpful to add a name field in `exclude`?
something similair to this:

```yaml
exclude:
- name: ci-workers
  address: 10.10.10.10-10.10.10.10.15
- name: dhcp
  address: 10.10.10.4
```

**Comment by schrej** [comment]
Not a big fan of that.
Imo you only need a name or a description if you have a lot of exclusions. And in that case I'd argue that you should size down your pool or specify usable addresses as ranges.
