### ISSUE TITLE
ipam provider does not support capi v1.6.0

### ISSUE THREAD

**Issue by mslga** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#218]
ipam provider does not support capi v1.6.0, apparently because CAPI stopped serving the alpha API version 

is it possible to update ipam provider to support new CAPI within half a year?

**Comment by mcbenjemaa** [comment]
@mslga the issue is already fixed and will be out in the next release.
check the planning: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/releases/release-1.7.md

**Comment by mslga** [comment]
Appreciate for the information. We will wait for the new release
