### ISSUE TITLE
Two distinct globalinclusterippools can contain same ip ranges

### ISSUE THREAD

**Issue by lukastopiarz** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#272]
Hello there,

I created by accident two globalinclusteripool CRs with unique names and same IP address ranges. No complaints from the admission webhook, nor IPAM operator. Cluster API is happily rolling new nodes with the same IP addresses 😯

<img width="999" alt="image" src="https://github.com/user-attachments/assets/c581fe21-e7f1-459f-afba-84aa465e181c">
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/663cb1c9-7868-4581-a99b-4520e34bc623">
Cluster nodes with same IPs!
<img width="1655" alt="image" src="https://github.com/user-attachments/assets/6370b844-559a-41aa-a26a-f59bca74d756">

Shouldn't be this behaviour somehow checked and prohibited?

**Comment by schrej** [comment]
I think that's debatable. The in-cluster IPAM provider manages IP addresses in pools, but it does not manage the pools. Cluster Nodes can use the same subnet as long as your network setup allows it. Therefore there might be cases where someone wants to have two separate pools that use the same subnet, but live in e.g. two different data centers.

We could consider making this an optional feature, but then the question arises whether overlap validation should only cover global pools and regular pools per namespace, or all pools, regardless whether they're namespaced or global.
