### ISSUE TITLE
Build image for arm

### ISSUE THREAD

**Issue by CharlieR-o-o-t** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#285]
It will be good to have image for arm64

**Comment by schrej** [comment]
Have you tested the image on ARM? It should be multi-platform and support both amd64 and arm64.

More could be added to the Makefile, but I do not see a reason to. https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/blob/main/Makefile#L28

**Comment by CharlieR-o-o-t** [comment]
@schrej , sorry, I meant upload arm image to official repo:
ghcr.io/telekom/cluster-api-ipam-provider-in-cluster
