### ISSUE TITLE
IPAM Provider not found

### ISSUE THREAD

**Issue by jueklu** [kubernetes-sigs/cluster-api-ipam-provider-in-cluster#292]
Hi there,

I hope I'm not the only one experiencing this, but when I try to initialize the ClusterAPI with vSphere provider and also the IPAM provider with the following command: `clusterctl init --infrastructure vsphere --ipam incluster`

I get the following shell output:

```shell
Fetching providers
Error: failed to get provider components for the "incluster" provider: failed to get configuration for the IPAMProvider with name incluster. Please check the provider name and/or add configuration for new providers using the .clusterctl config file
```

Sometimes it also happens that it cant find the `ipam-components.yaml` file.

Here is my CAPI config `~/.cluster-api/clusterctl.yaml`:

```shell
# vSphere Credentials
VSPHERE_USERNAME: "Administrator@vsphere.intern"
VSPHERE_PASSWORD: "my-secure-pw"

# vSphere Resources
VSPHERE_SERVER: "vcsa1.vsphere.intern"
VSPHERE_DATACENTER: "Datacenter"
VSPHERE_DATASTORE: "datastore1"
VSPHERE_NETWORK: "VM Network"

VSPHERE_RESOURCE_POOL: "*/Resources"
VSPHERE_FOLDER: "k8s"

VSPHERE_STORAGE_POLICY: ""
VSPHERE_TLS_THUMBPRINT: "0D:C8..."


# vSphere VM Template
VSPHERE_TEMPLATE: "ubuntu-2004-kube-v1.28.0"

# Public SSH key to access the VMs
VSPHERE_SSH_AUTHORIZED_KEY: "ssh-rsa AAAA..."

# Kubernetes
KUBERNETES_VERSION: "v1.28.0"
CPI_IMAGE_K8S_VERSION: "v1.28.0"
VSPHERE_CONTROL_PLANE_ENDPOINT: "192.168.70.55"
CONTROL_PLANE_ENDPOINT_IP: "192.168.70.55"

providers:
  - name: in-cluster
    url: https://github.com/kubernetes-sigs/cluster-api-ipam-provider-in-cluster/releases/latest/ipam-components.yaml
    type: IPAMProvider
```

**Environment:**

KIND version: kind v0.24.0 go1.22.6 linux/amd64
CAPI version: clusterctl version: &version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.3", GitCommit:"945c938ce3e093c71950e022de4253373f911ae8", GitTreeState:"clean", BuildDate:"2024-09-10T16:29:18Z", GoVersion:"go1.22.7", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: v1.31.1
Kustomize Version: v5.4.2
Server Version: v1.31.0

Ubuntu 25.04
vSphere 8

**Comment by schrej** [comment]
The provider is named `in-cluster` in clusterctl. Could you try with that?

**Comment by jueklu** [comment]
Ah, thank you very much!

Initializing the cluster API with the following command solved it:
````shell
clusterctl init --infrastructure vsphere --ipam in-cluster
```

Friendly regards,
Jürgen
